---
- name: aws exists
  become_user: "{{ user }}"
  command: which aws
  register: aws_exists
  ignore_errors: yes

- name: download aws cli
  when: not aws_exists.rc == 0
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    mode: '0644'

- name: unzip aws cli
  when: not aws_exists.rc == 0
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes

- name: install aws cli
  become: true
  when: not aws_exists.rc == 0
  ansible.builtin.command:
    cmd: /tmp/aws/install
  args:
    creates: /usr/local/bin/aws
