---
- name: install debugging tools
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - bpfcc-tools
    - bpftrace
    - strace
    - gdb
    - dwarfdump
    - gcc-multilib
    - g++-multilib
    - libc6-dev-i386
    - nasm
    - libelf-dev
    - linux-tools-generic
    - linux-cloud-tools-generic

- name: download .gdbinit-gef.py using Ansible
  become_user: "{{ user }}"
  ansible.builtin.get_url:
    url: https://gef.blah.cat/py
    dest: ~/.gdbinit-gef.py
    mode: '0644'

- name: add 'source ~/.gdbinit-gef.py' to ~/.gdbinit
  become_user: "{{ user }}"
  ansible.builtin.lineinfile:
    path: ~/.gdbinit
    line: 'source ~/.gdbinit-gef.py'
    create: yes

