---
- name: Install debugging tools
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - bpfcc-tools
    - bpftrace
    - strace
    - gdb
    - dwarfdump
    - gcc-multilib
    - g++-multilib
    - libc6-dev-i386
    - nasm
    - libelf-dev
    - linux-tools-generic
    - linux-cloud-tools-generic
