---
- name: install debugging tools
  apt:
    name:
      - build-essential
      - bpfcc-tools
      - bpftrace
      - strace
      - gdb
      - dwarfdump
      - gcc-multilib
      - g++-multilib
      - libc6-dev-i386
      - nasm
      - valgrind
      - massif-visualizer
      - libelf-dev
      - linux-tools-generic
      - linux-cloud-tools-generic
    state: present

- name: download .gdbinit-gef.py using Ansible
  become_user: "{{ user }}"
  ansible.builtin.get_url:
    url: https://gef.blah.cat/py
    dest: ~/.gdbinit-gef.py
    mode: '0644'

- name: add 'source ~/.gdbinit-gef.py' to ~/.gdbinit
  become_user: "{{ user }}"
  ansible.builtin.lineinfile:
    path: ~/.gdbinit
    line: 'source ~/.gdbinit-gef.py'
    create: yes
