---
- name: add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: install docker ce
  apt:
    update_cache: yes
    name: docker-ce
    state: present

- name: add user to docker group
  become: yes
  become_method: sudo
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
