---
- name: check if golang exists
  become_user: "{{ user }}"
  command: which go
  register: go_exists
  ignore_errors: yes

- name: install go
  when: not go_exists.rc == 0
  become_user: "{{ user }}"
  get_url:
    url: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
  register: go_download

- name: extract go archive
  when: not go_exists.rc == 0
  become: yes
  unarchive:
    src: "{{ go_download.dest }}"
    dest: "/usr/local"
    remote_src: yes
    owner: "{{ user }}"
    group: "{{ user }}"

- name: install delve
  become_user: "{{ user }}"
  command:
    /usr/local/go/bin/go install github.com/go-delve/delve/cmd/dlv@latest

- name: install gopls
  become_user: "{{ user }}"
  command:
    /usr/local/go/bin/go install golang.org/x/tools/gopls@latest

- name: install gofumpt
  become_user: "{{ user }}"
  command:
    /usr/local/go/bin/go install mvdan.cc/gofumpt@latest

- name: install golangci-lint-langserver
  become_user: "{{ user }}"
  command:
    /usr/local/go/bin/go install github.com/nametake/golangci-lint-langserver@latest

- name: install golines
  become_user: "{{ user }}"
  command:
    /usr/local/go/bin/go install github.com/segmentio/golines@latest
