---
- name: download kubectl binary
  get_url:
    url: https://dl.k8s.io/release/{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/amd64/kubectl
    dest: /tmp/kubectl
    owner: "{{ user }}"
    mode: '0755'

- name: move kubectl binary to /usr/local/bin/
  command: mv /tmp/kubectl /usr/local/bin/

- name: install krew plugins
  become_user: "{{ user }}"
  command: >
    sh -c "mkdir -p ~/.krew/bin &&
    cd ~/.krew &&
    curl -fsSL https://github.com/kubernetes-sigs/krew/releases/latest/download/krew-linux_amd64.tar.gz -o krew.tar.gz &&
    tar zxvf krew.tar.gz &&
    ./krew-linux_amd64 install krew &&
    ./bin/kubectl-krew install ctx &&
    ./bin/kubectl-krew install ns"
