---
- name: llvm build dir
  stat:
    path: "{{ llvm_build_dir_path }}"
  register: llvm_build_dir
  when: llvm_install

- name: check if clang exists
  command: which clang
  changed_when: false
  register: clang_exists
  ignore_errors: yes
  when: llvm_install

- name: check if llvm-readelf exists
  command: which llvm-readelf
  changed_when: false
  register: llvm_exists
  ignore_errors: yes
  when: llvm_install

- name: clone llvm
  when:
    - llvm_install
    - not llvm_build_dir.stat.exists
    - llvm_exists is failed
  git:
    repo: https://github.com/llvm/llvm-project.git
    dest: "{{ llvm_build_dir_path }}"
    version: "{{ llvm_version }}"
    depth: 1

- name: llvm cmake
  when:
    - llvm_install
    - llvm_exists is failed
  shell: |
    rm -rf build && mkdir build && cd build && \
    cmake \
      -DLLVM_ENABLE_PROJECTS=clang -G 'Unix Makefiles' \
      -DCMAKE_INSTALL_PREFIX={{ llvm_install_dir_path }} \
      -DLLVM_ENABLE_ASSERTIONS=No \
      -DCMAKE_BUILD_TYPE=Release \
      -DLLVM_ENABLE_PROJECTS='clang;;clang-tools-extra;lld;' \
      -DLLVM_TARGETS_TO_BUILD=all \
      ../llvm
  args:
    chdir: "{{ llvm_build_dir_path }}"

- name: llvm make
  when:
    - llvm_install
    - llvm_exists is failed
  shell: |
    make -j$(nproc)
  args:
    chdir: "{{ llvm_build_dir_path }}/build"

- name: llvm make clang
  when:
    - llvm_install
    - clang_exists is false
  shell: |
    make -j$(nproc) clang
  args:
    chdir: "{{ llvm_build_dir_path }}/build"

- name: llvm make install
  when:
    - llvm_install
    - llvm_exists is failed
  shell: |
    make install -j$(nproc)
  args:
    chdir: "{{ llvm_build_dir_path }}/build"

- name: llvm add path
  when: llvm_install
  template:
    src: llvm.conf-template.j2
    dest: "/etc/ld.so.conf.d/llvm-{{ llvm_version }}.conf"
    mode: 0644

- name: llvm run ldconfig
  command: ldconfig
  when: llvm_install

- name: llvm clean build dir
  when: llvm_install
  file:
    state: absent
    path: "{{ llvm_build_dir_path }}"
