---
- name: add nodejs apt key
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add nodejs 20.x ppa for apt repo
  become: yes
  apt_repository:
    repo: deb https://deb.nodesource.com/node_20.x bionic main
    update_cache: yes

- name: install nodejs
  become: yes
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: clean npm cache
  become: yes
  command: npm cache clean -f
  become_user: "{{ user }}"

- name: install n globally
  become: yes
  command: npm install -g n
  become_user: "{{ user }}"

- name: install stable version of Node.js
  become: yes
  command: n stable
  become_user: "{{ user }}"
