---
- name: python deps
  apt:
    name:
      - python3
      - python3-setuptools
      - python3-dev
      - python3-pip
      - python3-venv
    state: present

- name: pip deps
  become_user: "{{ user }}"
  pip:
    name:
      - black
      - radon
      - bandit
      - pylint
      - ipdb
      - neovim
      - doq
      - pytest
    state: present
