---
- name: check if tmux exists
  become_user: "{{ user }}"
  command: which tmux
  register: tmux_exists
  ignore_errors: yes

- name: tpm dir exists
  become_user: "{{ user }}"
  stat:
    path: "~/.tmux/plugins/tpm"
  register: tpm_dir

- name: resurrect exists
  become_user: "{{ user }}"
  stat:
    path: "~/.tmux/plugins/resurrect.tmux"
  register: resurrect

- name: install tmux
  when: not tmux_exists.rc == 0
  apt:
    name:
      - tmux
    state: present

- name: create plugins directory if it doesn't exist
  become_user: "{{ user }}"
  file:
    path: ~/.tmux/plugins
    state: directory
    mode: '0755'

- name: clone tpm repository
  become_user: "{{ user }}"
  when: not tpm_dir.stat.exists
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm

- name: download resurrect
  become_user: "{{ user }}"
  get_url:
    url: "https://github.com/tmux-plugins/tmux-resurrect/archive/master.tar.gz"
    dest: "~/.tmux/plugins/res.tar.gz"
    owner: "{{ user }}"
    mode: '0755'
  when: not resurrect.stat.exists

- name: unpack resurrect
  become_user: "{{ user }}"
  command: tar --strip-components=1 -xzf "~/.tmux/plugins/res.tar.gz" -C "~/.tmux/plugins/"
  when: not resurrect.stat.exists
