---
- name: tpm dir exists
  become_user: "{{ user }}"
  stat:
    path: "~/.tmux/plugins/tpm"
  register: tpm_dir

- name: resurrect exists
  become_user: "{{ user }}"
  stat:
    path: "~/.tmux/plugins/resurrect.tmux"
  register: resurrect

- name: install tmux
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - tmux

- name: create plugins directory if it doesn't exist
  become_user: "{{ user }}"
  file:
    path: ~/.tmux/plugins
    state: directory
    mode: '0755'

- name: clone tpm repository
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
  when: not tpm_dir.stat.exists

- name: unpack tmp
  become_user: "{{ user }}"
  command: tar --strip-components=1 -xzf "~/.tmux/plugins/tpm.tar.gz" -C "~/.tmux/plugins/"
  when: not tpm_dir.stat.exists

- name: download resurrect
  become_user: "{{ user }}"
  get_url:
    url: "https://github.com/tmux-plugins/tmux-resurrect/archive/master.tar.gz"
    dest: "~/.tmux/plugins/res.tar.gz"
    owner: "{{ user }}"
    mode: '0755'
  when: not resurrect.stat.exists

- name: unpack resurrect
  become_user: "{{ user }}"
  command: tar --strip-components=1 -xzf "~/.tmux/plugins/res.tar.gz" -C "~/.tmux/plugins/"
  when: not resurrect.stat.exists
