---
- name: tmux plugins
  become: true
  become_user: "{{ user }}"
  block:
    - name: create plugins directory if it doesn't exist
      ansible.builtin.file:
        path: "{{ user_home }}/.tmux/plugins"
        state: directory
        mode: '0755'

    - name: install tmux plugins
      ansible.builtin.git:
        repo: "https://github.com/tmux-plugins/{{ item }}.git"
        dest: "{{ user_home }}/.tmux/plugins/{{ item }}"
        update: true
      loop:
        - tpm
        - tmux-sensible
        - tmux-resurrect
        - tmux-yank
